### ISSUE TITLE
crystal 0.27.0 support

### ISSUE THREAD

**Issue by sam0x17** [sam0x17/gcf.cr#5]
Will have to wait for 0.27.1 due to an issue with alpine linux. This will come soon.

**Comment by sam0x17** [comment]
https://github.com/alpinelinux/aports/pull/5560

**Comment by sam0x17** [comment]
https://github.com/crystal-lang/crystal/pull/7067

**Comment by sam0x17** [comment]
fixed in https://github.com/crystal-lang/crystal/pull/7087, waiting for 0.27.1 tag https://github.com/crystal-lang/crystal/milestone/32

**Comment by RX14** [comment]
Fixed in https://github.com/alpinelinux/aports/commit/8ba9da3887a3d3030f4c85f2d148279c9bba012a

**Comment by sam0x17** [comment]
Thanks @RX14 

I will run the new build when I have a chance
